version: 2
jobs:
  build:
    environment:
      - APP_NAME:      openjdk
      - APP_VERSIONS: "8-jdk-xenial 8-jdk-slim-xenial 8-jre-slim-xenial"
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASS}

      - run:
          name: Build docker images for all versions
          command: |
            for v in ${APP_VERSIONS}; do
                docker build -t pure/${APP_NAME}:${v} $v
            done

      - run:
          name: Push docker images to registry
          command: |
            for v in ${APP_VERSIONS}; do
                docker push pure/${APP_NAME}:${v}
            done

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          context: pure-global
          filters:
            branches:
              only:
                - master
